In [1]:
import pandas as pd
import numpy as np

In [2]:
with open('input_data.txt') as f:
    input_lines = f.readlines()
input_lines[:10]

input_lines = [a.replace('\n','') for a in input_lines ]
input_lines[:10]

['....................................18..........889.270.....748.280...997.................617..............622........763............476....\n',
 '...529......434.....191..489...717...@.....................&....................939*7.....*....................606............760....*......\n',
 '....*...473....*221................$........182......812........493.84....793..........794.......589..407..41...*.....................68....\n',
 '..380.................553..559..105.....749.............*..........*.........*.............-968....@.....*..*....908..603...................\n',
 '.........................................#...600.........441..#833...490....366.........................225..488........&...456.........224.\n',
 '........288=......896*469..........831..........*....................*..............#...@.146.......*.............790#......%...194....@....\n',
 '..730.........................250+......./......359....=.462..............138...#.49..713.-........342...604*676....

In [4]:
pd.DataFrame(input_lines)

0
0    ....................................18...........
1    ...529......434.....191..489...717...@...........
2    ....*...473....*221................$........18...
3    ..380.................553..559..105.....749......
4    .........................................#...6...
..                                                 ...
135  ..........*....................*.*....*..........
136  ........249....291...........448.622..228........
137  ..................*173..817......................
138  ...32.674......-........%.....402/...........6...
139  .............885.................................

[140 rows x 1 columns]

In [5]:
input_lines_mod = [list(a) for a in input_lines]
input_lines_mod[0]

input_array = np.array(input_lines_mod)
input_array

['.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '1',
 '8',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '8',
 '8',
 '9',
 '.',
 '2',
 '7',
 '0',
 '.',
 '.',
 '.',
 '.',
 '.',
 '7',
 '4',
 '8',
 '.',
 '2',
 '8',
 '0',
 '.',
 '.',
 '.',
 '9',
 '9',
 '7',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '6',
 '1',
 '7',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '6',
 '2',
 '2',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '7',
 '6',
 '3',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '.',
 '4',
 '7',
 '6',
 '.',
 '.',
 '.',
 '.']

In [7]:
input_array.shape

(140, 140)

In [8]:
import re

In [9]:
bool(re.search("hi", "abcdefghijkl"))

True

In [10]:
bool(re.search("[^.\d]", "."))

False

In [11]:
bool(re.search("[^.\d]", "*"))

True

In [12]:
f = np.vectorize(lambda x: bool(re.search("[^.\d]", x)))

In [13]:
#f = (lambda x: bool(re.search("[^.\d]", x)))

In [14]:
f(input_array)[1].T

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [15]:
len(np.array(input_lines)[0])

140

In [16]:
symbol_coor = np.transpose(f(input_array).nonzero())
symbol_coor

array([[  1,  37],
       [  1,  59],
       [  1,  83],
       ...,
       [138, 100],
       [138, 114],
       [138, 129]], dtype=int64)

In [17]:
symbol_coor[0]

array([ 1, 37], dtype=int64)

In [ ]:
# cut off edges
# no row which is 0, n-1 or column which 0, n-1

x,y
x-1,y
x+1,y
x,y-1
x,y+1

x-1,y+1
x+1,y+1
x-1,y-1
x+1,y-1



In [ ]:
[1,3]

[2,[3, 6]]

In [19]:
new_coor = []

for x,y in symbol_coor:
    nxts=[(x-1,y),
        (x+1,y),
        (x,y-1),
        (x,y+1),
        (x-1,y+1),
        (x+1,y+1),
        (x-1,y-1),
        (x+1,y-1)]
    new_coor.extend(nxts)
    
new_coor

[(0, 37),
 (2, 37),
 (1, 36),
 (1, 38),
 (0, 38),
 (2, 38),
 (0, 36),
 (2, 36),
 (0, 59),
 (2, 59),
 (1, 58),
 (1, 60),
 (0, 60),
 (2, 60),
 (0, 58),
 (2, 58),
 (0, 83),
 (2, 83),
 (1, 82),
 (1, 84),
 (0, 84),
 (2, 84),
 (0, 82),
 (2, 82),
 (0, 90),
 (2, 90),
 (1, 89),
 (1, 91),
 (0, 91),
 (2, 91),
 (0, 89),
 (2, 89),
 (0, 133),
 (2, 133),
 (1, 132),
 (1, 134),
 (0, 134),
 (2, 134),
 (0, 132),
 (2, 132),
 (1, 4),
 (3, 4),
 (2, 3),
 (2, 5),
 (1, 5),
 (3, 5),
 (1, 3),
 (3, 3),
 (1, 15),
 (3, 15),
 (2, 14),
 (2, 16),
 (1, 16),
 (3, 16),
 (1, 14),
 (3, 14),
 (1, 35),
 (3, 35),
 (2, 34),
 (2, 36),
 (1, 36),
 (3, 36),
 (1, 34),
 (3, 34),
 (1, 112),
 (3, 112),
 (2, 111),
 (2, 113),
 (1, 113),
 (3, 113),
 (1, 111),
 (3, 111),
 (2, 56),
 (4, 56),
 (3, 55),
 (3, 57),
 (2, 57),
 (4, 57),
 (2, 55),
 (4, 55),
 (2, 67),
 (4, 67),
 (3, 66),
 (3, 68),
 (2, 68),
 (4, 68),
 (2, 66),
 (4, 66),
 (2, 77),
 (4, 77),
 (3, 76),
 (3, 78),
 (2, 78),
 (4, 78),
 (2, 76),
 (4, 76),
 (2, 91),
 (4, 91),
 (3, 90),
 (

In [20]:
np.array(new_coor)[:,0]

array([  0,   2,   1, ..., 139, 137, 139], dtype=int64)

In [21]:
new_coor

[(0, 37),
 (2, 37),
 (1, 36),
 (1, 38),
 (0, 38),
 (2, 38),
 (0, 36),
 (2, 36),
 (0, 59),
 (2, 59),
 (1, 58),
 (1, 60),
 (0, 60),
 (2, 60),
 (0, 58),
 (2, 58),
 (0, 83),
 (2, 83),
 (1, 82),
 (1, 84),
 (0, 84),
 (2, 84),
 (0, 82),
 (2, 82),
 (0, 90),
 (2, 90),
 (1, 89),
 (1, 91),
 (0, 91),
 (2, 91),
 (0, 89),
 (2, 89),
 (0, 133),
 (2, 133),
 (1, 132),
 (1, 134),
 (0, 134),
 (2, 134),
 (0, 132),
 (2, 132),
 (1, 4),
 (3, 4),
 (2, 3),
 (2, 5),
 (1, 5),
 (3, 5),
 (1, 3),
 (3, 3),
 (1, 15),
 (3, 15),
 (2, 14),
 (2, 16),
 (1, 16),
 (3, 16),
 (1, 14),
 (3, 14),
 (1, 35),
 (3, 35),
 (2, 34),
 (2, 36),
 (1, 36),
 (3, 36),
 (1, 34),
 (3, 34),
 (1, 112),
 (3, 112),
 (2, 111),
 (2, 113),
 (1, 113),
 (3, 113),
 (1, 111),
 (3, 111),
 (2, 56),
 (4, 56),
 (3, 55),
 (3, 57),
 (2, 57),
 (4, 57),
 (2, 55),
 (4, 55),
 (2, 67),
 (4, 67),
 (3, 66),
 (3, 68),
 (2, 68),
 (4, 68),
 (2, 66),
 (4, 66),
 (2, 77),
 (4, 77),
 (3, 76),
 (3, 78),
 (2, 78),
 (4, 78),
 (2, 76),
 (4, 76),
 (2, 91),
 (4, 91),
 (3, 90),
 (

In [37]:
input_array

array([['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ...,
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.']], dtype='<U1')

In [22]:
bool_m = np.zeros(input_array.shape,dtype=bool)
bool_m

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [23]:
new_coor[0]

(0, 37)

In [24]:
bool_m[np.array(new_coor)[:,0],np.array(new_coor)[:,1]] = True
bool_m[0].T

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [25]:
d = np.vectorize(lambda x: bool(re.search("[\d]", x)))
digits = d(input_array)
digits[0].T

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True, False,  True,  True,
        True, False, False, False, False, False,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False, False,

In [26]:
bool_m[0].T + digits[0].T

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False,  True,  True,  True, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False, False,

In [27]:
overlap = bool_m & digits
overlap[0].T

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [28]:
overlap.nonzero()

(array([  0,   0,   0, ..., 139, 139, 139], dtype=int64),
 array([ 36,  37,  60, ..., 101, 115, 128], dtype=int64))

In [29]:
digits_all = {}

for i in range(len(input_lines)):
    digits_all[i] = [(m.start(0), m.end(0)) for m in re.finditer("\d+",input_lines[i])]
    
digits_all

{0: [(36, 38),
  (48, 51),
  (52, 55),
  (60, 63),
  (64, 67),
  (70, 73),
  (90, 93),
  (107, 110),
  (118, 121),
  (133, 136)],
 1: [(3, 6),
  (12, 15),
  (20, 23),
  (25, 28),
  (31, 34),
  (80, 83),
  (84, 85),
  (111, 114),
  (126, 129)],
 2: [(8, 11),
  (16, 19),
  (44, 47),
  (53, 56),
  (64, 67),
  (68, 70),
  (74, 77),
  (87, 90),
  (97, 100),
  (102, 105),
  (107, 109),
  (134, 136)],
 3: [(2, 5),
  (22, 25),
  (27, 30),
  (32, 35),
  (40, 43),
  (92, 95),
  (113, 116),
  (118, 121)],
 4: [(45, 48),
  (57, 60),
  (63, 66),
  (69, 72),
  (76, 79),
  (104, 107),
  (109, 112),
  (124, 127),
  (136, 139)],
 5: [(8, 11), (18, 21), (22, 25), (35, 38), (90, 93), (114, 117), (128, 131)],
 6: [(2, 5),
  (30, 33),
  (48, 51),
  (57, 60),
  (74, 77),
  (82, 84),
  (86, 89),
  (99, 102),
  (105, 108),
  (109, 112),
  (137, 140)],
 7: [(9, 12),
  (19, 22),
  (38, 41),
  (52, 55),
  (62, 65),
  (78, 81),
  (94, 97),
  (119, 122),
  (125, 128),
  (133, 136)],
 8: [(5, 8), (29, 31), (35, 37)

In [30]:
type(input_lines)

list

In [31]:
np.array(input_lines)

array(['....................................18..........889.270.....748.280...997.................617..............622........763............476....',
       '...529......434.....191..489...717...@.....................&....................939*7.....*....................606............760....*......',
       '....*...473....*221................$........182......812........493.84....793..........794.......589..407..41...*.....................68....',
       '..380.................553..559..105.....749.............*..........*.........*.............-968....@.....*..*....908..603...................',
       '.........................................#...600.........441..#833...490....366.........................225..488........&...456.........224.',
       '........288=......896*469..........831..........*....................*..............#...@.146.......*.............790#......%...194....@....',
       '..730.........................250+......./......359....=.462..............138...#.49..

In [32]:
valid_digits = 0

for k,v in digits_all.items():
    for s,e in v:
        #True in overlap[k,s:e]
        if any(overlap[k,s:e]):
            
            valid_digits += int(input_lines[k][s:e])
            
valid_digits

535078

In [103]:
with open('input_data.txt') as f:
    input_lines = f.readlines()
input_lines[:10]

input_lines = [a.replace('\n','') for a in input_lines ]
input_lines[:10]

['....................................18..........889.270.....748.280...997.................617..............622........763............476....',
 '...529......434.....191..489...717...@.....................&....................939*7.....*....................606............760....*......',
 '....*...473....*221................$........182......812........493.84....793..........794.......589..407..41...*.....................68....',
 '..380.................553..559..105.....749.............*..........*.........*.............-968....@.....*..*....908..603...................',
 '.........................................#...600.........441..#833...490....366.........................225..488........&...456.........224.',
 '........288=......896*469..........831..........*....................*..............#...@.146.......*.............790#......%...194....@....',
 '..730.........................250+......./......359....=.462..............138...#.49..713.-........342...604*676.........=.....*

In [104]:
# 2nd part
f2 = np.vectorize(lambda x: bool(re.search("[*]", x)))
f2(input_array)[1].T

array([False, False, False,  True, False, False, False, False, False,
       False])

In [85]:
# 2nd part
#f2 = np.vectorize(lambda x: bool(re.search("[^.\d\*]", x)))
#f2(input_array)[1].T

In [105]:
input_lines_mod = [list(a) for a in input_lines]
input_lines_mod[0]

input_array = np.array(input_lines_mod)
input_array

array([['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ...,
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.'],
       ['.', '.', '.', ..., '.', '.', '.']], dtype='<U1')

In [106]:
symbol_coor2 = np.transpose(f2(input_array).nonzero())
symbol_coor2

array([[  1,  83],
       [  1,  90],
       [  1, 133],
       [  2,   4],
       [  2,  15],
       [  2, 112],
       [  3,  56],
       [  3,  67],
       [  3,  77],
       [  3, 105],
       [  3, 108],
       [  5,  21],
       [  5,  48],
       [  5,  69],
       [  5, 100],
       [  6, 108],
       [  6, 127],
       [  7,   4],
       [  7,  60],
       [  7, 136],
       [  8,  11],
       [  8,  22],
       [  8,  65],
       [  8, 106],
       [  9,  36],
       [  9,  88],
       [ 10, 118],
       [ 11,  16],
       [ 11,  82],
       [ 11, 127],
       [ 12,  61],
       [ 13,  50],
       [ 14,  37],
       [ 14, 123],
       [ 14, 130],
       [ 15, 116],
       [ 16,  38],
       [ 17,  16],
       [ 17,  52],
       [ 17,  61],
       [ 17,  70],
       [ 17, 135],
       [ 18,   9],
       [ 18,  22],
       [ 18,  83],
       [ 18,  86],
       [ 18, 110],
       [ 19,  77],
       [ 19, 125],
       [ 20,   6],
       [ 20,  13],
       [ 20,  26],
       [ 20,

In [89]:
new_coor2 = []

for x,y in symbol_coor2:
    nxts=[(x-1,y),
        (x+1,y),
        (x,y-1),
        (x,y+1),
        (x-1,y+1),
        (x+1,y+1),
        (x-1,y-1),
        (x+1,y-1)]
    new_coor2.extend(nxts)
    
new_coor2

[(0, 3),
 (2, 3),
 (1, 2),
 (1, 4),
 (0, 4),
 (2, 4),
 (0, 2),
 (2, 2),
 (3, 3),
 (5, 3),
 (4, 2),
 (4, 4),
 (3, 4),
 (5, 4),
 (3, 2),
 (5, 2),
 (7, 5),
 (9, 5),
 (8, 4),
 (8, 6),
 (7, 6),
 (9, 6),
 (7, 4),
 (9, 4)]

In [91]:
#bool_m2 = np.zeros(input_array.shape,dtype=bool)
#bool_m2

In [92]:
#bool_m2[np.array(new_coor2)[:,0],np.array(new_coor2)[:,1]] = True
#bool_m2[0].T

In [93]:
#overlap2 = bool_m2 & digits
#overlap2[0].T

In [107]:
digits_all = {}

for i in range(len(input_lines)):
    digits_all[i] = [(m.start(0), m.end(0)) for m in re.finditer("\d+",input_lines[i])]
    
digits_all

{0: [(36, 38),
  (48, 51),
  (52, 55),
  (60, 63),
  (64, 67),
  (70, 73),
  (90, 93),
  (107, 110),
  (118, 121),
  (133, 136)],
 1: [(3, 6),
  (12, 15),
  (20, 23),
  (25, 28),
  (31, 34),
  (80, 83),
  (84, 85),
  (111, 114),
  (126, 129)],
 2: [(8, 11),
  (16, 19),
  (44, 47),
  (53, 56),
  (64, 67),
  (68, 70),
  (74, 77),
  (87, 90),
  (97, 100),
  (102, 105),
  (107, 109),
  (134, 136)],
 3: [(2, 5),
  (22, 25),
  (27, 30),
  (32, 35),
  (40, 43),
  (92, 95),
  (113, 116),
  (118, 121)],
 4: [(45, 48),
  (57, 60),
  (63, 66),
  (69, 72),
  (76, 79),
  (104, 107),
  (109, 112),
  (124, 127),
  (136, 139)],
 5: [(8, 11), (18, 21), (22, 25), (35, 38), (90, 93), (114, 117), (128, 131)],
 6: [(2, 5),
  (30, 33),
  (48, 51),
  (57, 60),
  (74, 77),
  (82, 84),
  (86, 89),
  (99, 102),
  (105, 108),
  (109, 112),
  (137, 140)],
 7: [(9, 12),
  (19, 22),
  (38, 41),
  (52, 55),
  (62, 65),
  (78, 81),
  (94, 97),
  (119, 122),
  (125, 128),
  (133, 136)],
 8: [(5, 8), (29, 31), (35, 37)

In [108]:
mult_valid_digits = 0


for x,y in symbol_coor2:
    
    mult_iter = []
    
    nxts=[(x-1,y),
        (x+1,y),
        (x,y-1),
        (x,y+1),
        (x-1,y+1),
        (x+1,y+1),
        (x-1,y-1),
        (x+1,y-1)]
    
    for row, digs in digits_all.items():
        for b,c in digs:
            if any((b<=j<c) and (i==row) for i,j in nxts):
                mult_iter.append(input_lines[row][b:c])

    if len(mult_iter)==2:
        mult_valid_digits += int(mult_iter[0])*int(mult_iter[1])
    
            
mult_valid_digits

75312571