In [1]:
import numpy as np

In [5]:
with open('small_input.txt') as f:
    input_lines = f.readlines()

input_lines = [a.replace('\n','') for a in input_lines ]
input_lines[:10]

['#.##..##.',
 '..#.##.#.',
 '##......#',
 '##......#',
 '..#.##.#.',
 '..##..##.',
 '#.#.##.#.',
 '',
 '#...##..#',
 '#....#..#']

In [140]:
with open('input_string.txt') as f:
    input_lines = f.readlines()

input_lines = [a.replace('\n','') for a in input_lines ]
input_lines[:10]

['######..#....#.',
 '######.#.#.####',
 '##..###.##.#..#',
 '......######.#.',
 '#....###...##.#',
 '.#..#.###.#.##.',
 '.#..#..##.#.##.',
 '',
 '#.#....##....#.#.',
 '#.#....##....#.#.']

In [141]:
# list position of ' ' in input_lines
space_pos = [i for i, str in enumerate(input_lines) if str == '']
space_pos.append(len(input_lines))
space_pos

[7,
 21,
 31,
 49,
 63,
 71,
 87,
 97,
 107,
 125,
 133,
 141,
 153,
 171,
 185,
 193,
 207,
 225,
 243,
 255,
 271,
 281,
 291,
 309,
 325,
 337,
 355,
 371,
 387,
 399,
 411,
 423,
 435,
 449,
 467,
 481,
 495,
 507,
 515,
 533,
 547,
 557,
 571,
 585,
 599,
 611,
 621,
 629,
 643,
 661,
 679,
 695,
 709,
 725,
 741,
 755,
 773,
 789,
 799,
 817,
 829,
 837,
 847,
 863,
 879,
 895,
 903,
 915,
 931,
 943,
 957,
 967,
 977,
 987,
 999,
 1015,
 1025,
 1043,
 1053,
 1067,
 1077,
 1085,
 1101,
 1111,
 1125,
 1143,
 1153,
 1165,
 1173,
 1185,
 1201,
 1215,
 1223,
 1237,
 1245,
 1261,
 1279,
 1293,
 1303,
 1311]

In [145]:
input_lines_mod = []
beg = -1
for i in space_pos:
    chunk = [list(b) for b in input_lines[beg+1:i]]
    chunk = [[1 if a == '#' else 0 for a in b] for b in chunk]
    input_lines_mod.append(np.array(chunk))
    beg = i

input_lines_mod

[array([[1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
        [1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0],
        [1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1],
        [0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
        [0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0]]),
 array([[1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
        [1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
        [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1],
        [0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
        [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0],
   

In [146]:
# for i in input_lines_mod:
#     #replace # with 1 and . with 0 and make them integers
#     i[i == '#'] = 1
#     i[i == '.'] = 0
#     i = i.astype(int)


# input_lines_mod

In [147]:
# change dtype of input_lines_mod to int
#input_lines_mod = np.array(input_lines_mod).astype(int)

#input_lines_mod[0][0][0]
#input_lines_mod

In [109]:
input_lines_mod[0][0:2,:]

array([[1, 0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 1, 0]])

In [114]:
(input_lines_mod[0][0:3,:])

array([[1, 0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1]])

In [148]:
row_list = []
for i in input_lines_mod:

    rows = i.shape[0]
    cols = i.shape[1]
    #print(rows,cols)

    for row in list(range(0,(rows-1))):

        upper_half = i[0:row+1,:]
        lower_half = i[row+1:rows,:]
        size = min(len(upper_half),len(lower_half))
        upper_half = np.flipud(upper_half)[0:size,:]
        lower_half = lower_half[0:size,:]
        
        if np.array_equal(upper_half,lower_half):
            #print('Horizontal split is',row)
            row_list.append((1+row)*100)

row_list
   
        

[100,
 300,
 600,
 700,
 100,
 400,
 200,
 1100,
 1300,
 400,
 100,
 100,
 800,
 1300,
 1100,
 1400,
 1400,
 500,
 100,
 100,
 100,
 300,
 100,
 200,
 1000,
 200,
 700,
 200,
 1000,
 300,
 1100,
 1100,
 900,
 1000,
 400,
 100,
 1500,
 1400,
 500,
 400,
 200,
 200,
 100,
 200,
 200,
 100,
 100,
 100,
 600,
 1100,
 200,
 700,
 600,
 700,
 200,
 1000,
 200,
 300,
 300,
 600,
 600]

In [151]:
len(input_lines_mod)

100

In [149]:
col_list = []

for i in input_lines_mod:

    rows = i.shape[0]
    cols = i.shape[1]
    #print(rows,cols)

    for col in list(range(0,(cols-1))):
        #print(col)

        left_half = i[:,0:col+1]
        right_half = i[:,col+1:cols]
        size = min((left_half.shape[1]),(right_half.shape[1]))
        left_half = np.fliplr(left_half)[:,0:size]
        right_half = right_half[:,0:size]
        
        if np.array_equal(left_half,right_half):
            #print('Vertical split is',col)
            col_list.append(col+1)

col_list
        

[3,
 10,
 16,
 14,
 12,
 4,
 4,
 2,
 5,
 14,
 1,
 9,
 3,
 15,
 14,
 7,
 7,
 10,
 12,
 12,
 2,
 1,
 2,
 4,
 12,
 15,
 1,
 14,
 1,
 1,
 12,
 1,
 10,
 12,
 2,
 3,
 13,
 13,
 2]

In [150]:
sum(row_list) + sum(col_list)

33195